CREATE EXTENSION IF NOT EXISTS vector;

-- Users table
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    is_admin INTEGER NOT NULL DEFAULT 0,

    -- Encrypted user name
    encrypted_name BYTEA NOT NULL,
    name_nonce BYTEA NOT NULL,
    name_hash TEXT NOT NULL UNIQUE,

    -- Encrypted password
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    password_algo TEXT NOT NULL DEFAULT 'argon2id',

    -- Encrypted phone
    encrypted_phone BYTEA NOT NULL,
    phone_nonce BYTEA NOT NULL,
    phone_hash TEXT NOT NULL,
    phone_verified INTEGER NOT NULL DEFAULT 0,
    sms_opted_out INTEGER NOT NULL DEFAULT 0,

    -- Notification settings
    last_sms_sent_at TIMESTAMP
);
CREATE INDEX idx_user_deleted_at ON users(deleted_at);
CREATE INDEX idx_user_name_hash ON users(name_hash);
CREATE INDEX idx_user_phone_hash ON users(phone_hash);
CREATE UNIQUE INDEX idx_users_phone_hash_active
    ON users(phone_hash) WHERE deleted_at IS NULL;
CREATE INDEX idx_users_last_sms_sent ON users(last_sms_sent_at);

-- Phone verification codes table
CREATE TABLE phone_verification (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phone_e64 TEXT NOT NULL,
    verification_code TEXT NOT NULL,
    purpose TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id),
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (purpose = 'register' AND user_id IS NULL) OR
        (purpose = 'change_phone' AND user_id IS NOT NULL)
    )
);
CREATE INDEX idx_phone_verification_phone_e64 ON phone_verification(phone_e64);
CREATE INDEX idx_phone_verification_purpose
    ON phone_verification(phone_e64, purpose, user_id);
CREATE INDEX idx_phone_verification_code ON phone_verification(verification_code);
CREATE INDEX idx_phone_verification_created_at ON phone_verification(created_at);

-- Account recovery sessions (inbound SMS proof; ephemeral)
CREATE TABLE account_recovery (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_token_hash TEXT NOT NULL UNIQUE,
    code_hash TEXT NOT NULL UNIQUE,
    user_id INTEGER REFERENCES users(id),
    failure TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_account_recovery_expires_at ON account_recovery(expires_at);
CREATE INDEX idx_account_recovery_user_id ON account_recovery(user_id);

-- Locations table
CREATE TABLE locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    raw_text TEXT UNIQUE NOT NULL CHECK (length(raw_text) > 0),
    city TEXT NOT NULL,
    admin_area TEXT NOT NULL,
    country TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);
CREATE INDEX idx_location_raw_text ON locations(raw_text);

-- Categories table
CREATE TABLE categories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    seed_ad_file TEXT,
    image_file TEXT,
    facets TEXT NOT NULL DEFAULT '[]' -- JSON array of facet keys
);

-- Ads table
-- States: active (both null), inactive (inactive_at set), deleted (deleted_at set; zombie)
CREATE TABLE ads (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES categories(id),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    inactive_at TIMESTAMP,
    deleted_at TIMESTAMP,
    user_id INTEGER NOT NULL REFERENCES users(id),
    image_count INTEGER DEFAULT 0,
    location_id INTEGER REFERENCES locations(id),
    tags TEXT NOT NULL DEFAULT '[]', -- JSON array of {label, value}
    embedding vector(768),
    vector_metadata JSONB
);
CREATE INDEX idx_ads_category ON ads(category_id);
CREATE INDEX idx_ads_embedding ON ads USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_ads_vector_metadata ON ads USING gin (vector_metadata);
CREATE INDEX idx_ads_inactive_at ON ads(inactive_at);
CREATE INDEX idx_ads_deleted_at ON ads(deleted_at);

-- Ad facet values table (one row per ad+facet; see internal/facet)
CREATE TABLE ad_facets (
    ad_id INTEGER NOT NULL REFERENCES ads(id),
    key   TEXT NOT NULL,
    num   INTEGER, -- Int/Money amounts (price, mileage, hours, year)
    text  TEXT,    -- currency (Money), unit (mi/km), or Enum selection
    PRIMARY KEY (ad_id, key)
);
CREATE INDEX idx_ad_facets_key_num ON ad_facets(key, num) WHERE num IS NOT NULL;
CREATE INDEX idx_ad_facets_key_text ON ad_facets(key, text) WHERE text IS NOT NULL;

-- Bookmarks table
CREATE TABLE bookmarks (
    user_id INTEGER NOT NULL REFERENCES users(id),
    ad_id INTEGER NOT NULL REFERENCES ads(id),
    bookmarked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, ad_id)
);
CREATE INDEX idx_bookmarks_user ON bookmarks(user_id);
CREATE INDEX idx_bookmarks_ad ON bookmarks(ad_id);

CREATE TABLE user_ad_clicks (
    ad_id INTEGER NOT NULL REFERENCES ads(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    click_count INTEGER NOT NULL DEFAULT 1,
    last_clicked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ad_id, user_id)
);
CREATE INDEX idx_user_ad_clicks_user ON user_ad_clicks(user_id);
CREATE INDEX idx_user_ad_clicks_ad ON user_ad_clicks(ad_id);

CREATE TABLE user_ad_image_clicks (
    ad_id INTEGER NOT NULL REFERENCES ads(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    image_index INTEGER NOT NULL,
    click_count INTEGER NOT NULL DEFAULT 1,
    last_clicked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ad_id, user_id, image_index)
);
CREATE INDEX idx_user_ad_image_clicks_user ON user_ad_image_clicks(user_id);
CREATE INDEX idx_user_ad_image_clicks_ad ON user_ad_image_clicks(ad_id);

-- Conversations table
CREATE TABLE conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ad_id INTEGER NOT NULL REFERENCES ads(id),
    owner_id INTEGER NOT NULL REFERENCES users(id),
    inquirer_id INTEGER NOT NULL REFERENCES users(id),
    owner_has_unread INTEGER NOT NULL DEFAULT 0,
    inquirer_has_unread INTEGER NOT NULL DEFAULT 0,
    rock_thrower_id INTEGER REFERENCES users(id), -- NULL = no rock (private), NOT NULL = public, owner_id = bound to inquirer, inquirer_id = bound to ad
    rock_thrown_at TIMESTAMP, -- Only valid if rock_thrower_id IS NOT NULL
    journal TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(ad_id, inquirer_id)
);
CREATE INDEX idx_conversations_owner ON conversations(owner_id);
CREATE INDEX idx_conversations_inquirer ON conversations(inquirer_id);
CREATE INDEX idx_conversations_ad ON conversations(ad_id);
CREATE INDEX idx_conversations_rock_thrower ON conversations(rock_thrower_id);
CREATE INDEX idx_conversations_updated_at ON conversations(updated_at);

-- Cached LLM arbitrator opinions for public rock conversations
CREATE TABLE rock_opinions (
    conversation_id INTEGER PRIMARY KEY REFERENCES conversations(id),
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    summary TEXT NOT NULL,
    assessment INTEGER NOT NULL CHECK (assessment BETWEEN 1 AND 10),
    assessment_detail TEXT NOT NULL,
    resolution TEXT NOT NULL,
    reasoning TEXT NOT NULL
);

-- SMS notification queue table
CREATE TABLE sms_notification_queue (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipient_user_id INTEGER NOT NULL REFERENCES users(id),
    conversation_id INTEGER NOT NULL REFERENCES conversations(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (recipient_user_id) REFERENCES users(id),
    FOREIGN KEY (conversation_id) REFERENCES conversations(id)
);
CREATE INDEX idx_sms_queue_recipient_status ON sms_notification_queue(recipient_user_id, status);
CREATE INDEX idx_sms_queue_status_created ON sms_notification_queue(status, created_at);
CREATE INDEX idx_sms_queue_processed_at ON sms_notification_queue(processed_at);